exp_name: test
model: MalariaVAE
hyperparams:
  batch_size: 64
  learning_rate: 1.0e-4
  nepochs: 2
  model:
    hidden_size: 2
  remove_cell_boundary: True
logger:
  project: deep-learning-malaria-vae